FROM python:2

# Install python and clone script from github
RUN \

  # script to split intervals
    wget https://github.com/yejinyou/arvados-pipelines/blob/master/scripts_revised/workflow/gatk-split-interval-list.py


CMD ["/bin/bash"]