FROM python:2

# Install python and clone script from github
RUN \

  # script to turn dictionary into interval list
    wget https://raw.githubusercontent.com/yejinyou/arvados-pipelines/master/scripts_revised/workflow/gatk-create-interval-lists.py

CMD ["/bin/bash"]