FROM python:2


# Install python and clone script from github
RUN \
  wget https://raw.githubusercontent.com/yejinyou/arvados-pipelines/master/crunch_scripts/gatk-split-interval-list.py


CMD ["/bin/bash"]

