FROM python:2

#install python and clone scriptfrom github
RUN \
  wget https://raw.githubusercontent.com/yejinyou/arvados-pipelines/master/scripts_revised/create_interval_list/gatk-create-interval-lists.py
  
CMD ["/bin/bash"]
